# Generated by Django 5.1 on 2024-11-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuaje',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
