# Generated by Django 5.1 on 2024-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tatuaje_realizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('tamano', models.CharField(choices=[('pequeno', 'Hasta 10 cm'), ('mediano', 'Hasta 20 cm'), ('grande', 'Más de 20 cm')], max_length=10)),
                ('tipo', models.CharField(choices=[('color', 'A color'), ('bn', 'Blanco y negro')], max_length=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tatuaje',
            name='realizado',
            field=models.BooleanField(default=True),
        ),
    ]
