# Generated by Django 5.1 on 2024-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cotizacionpersonalizada_alter_tatuaje_realizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuaje',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='tatuaje',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
