# Generated by Django 5.1 on 2024-11-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tatuaje_imagen_alter_tatuaje_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatuajePersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamano_max_cm', models.IntegerField()),
                ('precio_base', models.IntegerField()),
                ('costo_color', models.IntegerField()),
                ('costo_bn', models.IntegerField(default=0)),
            ],
        ),
    ]
